<?php

namespace MyProCache\Options;

class Defaults
{
    public static function all(): array
    {
        return array(
            'cache_backend'                => 'disk',
            'cache_logged_in_mode'         => 'bypass',
            'cache_rest_api'               => true,
            'cache_vary_device'            => true,
            'cache_vary_role'              => false,
            'cache_vary_lang'              => false,
            'cache_vary_cookie_allowlist'  => array(),
            'ttl_default'                  => 3600,
            'ttl_front_page'               => 600,
            'ttl_feed'                     => 900,
            'stale_while_revalidate'       => 300,
            'stale_if_error'               => 600,
            'purge_on_update'              => true,
            'purge_on_comment'             => true,
            'purge_ccu_cdn'                => true,
            'purge_schedule_enabled'       => false,
            'purge_schedule_patterns'      => array(),
            'exclude_urls'                 => array( '/cart', '/checkout', '/my-account', '/preview', '/\?s=' ),
            'exclude_cookies'              => array( 'woocommerce_items_in_cart', 'woocommerce_cart_hash' ),
            'exclude_user_agents'          => array( 'facebookexternalhit', 'bot', 'crawler' ),
            'exclude_query_args'           => array( 'nocache', 'preview', 'currency' ),
            'min_html'                     => false,
            'min_css'                      => false,
            'min_js'                       => false,
            'combine_css'                  => false,
            'combine_js'                   => false,
            'exclude_css_handles'          => array(),
            'exclude_js_handles'           => array(),
            'critical_css_auto'            => false,
            'critical_css_per_post_type'   => false,
            'css_async'                    => false,
            'js_defer'                     => false,
            'js_delay_until_interaction'   => false,
            'js_delay_allowlist'           => array(),
            'preload_keys'                 => array(),
            'dns_prefetch'                 => array(),
            'preconnect'                   => array(),
            'lazyload_images'              => true,
            'lazyload_iframes'             => true,
            'lqip_placeholders'            => false,
            'convert_webp'                 => false,
            'convert_avif'                 => false,
            'webp_avif_rewrite'            => false,
            'media_excludes'               => array(),
            'cdn_enabled'                  => false,
            'cdn_host'                     => '',
            'cdn_image_host'               => '',
            'cdn_static_host'              => '',
            'cdn_file_types'               => array( 'css', 'js', 'jpg', 'jpeg', 'png', 'gif', 'svg', 'webp', 'woff', 'woff2' ),
            'cf_enabled'                   => false,
            'cf_api_token'                 => '',
            'cf_zone_id'                   => '',
            'oc_enabled'                   => false,
            'oc_backend'                   => 'redis',
            'oc_host'                      => '127.0.0.1',
            'oc_port'                      => 6379,
            'oc_auth'                      => '',
            'oc_persistent_groups'         => array( 'options', 'site-options' ),
            'oc_compression'               => false,
            'preload_enabled'              => false,
            'preload_sitemaps'             => array(),
            'preload_concurrency'          => 2,
            'preload_interval_sec'         => 1,
            'preload_user_agent'           => 'MyProCache-Preload/1.0',
            'database_cleanup_revisions'   => false,
            'database_cleanup_autodrafts'  => false,
            'database_cleanup_trash_posts' => false,
            'database_cleanup_spam'        => false,
            'database_cleanup_transients'  => false,
            'database_cleanup_sessions'    => false,
            'database_optimize_tables'     => false,
            'toolbox_safe_mode'            => false,
            'toolbox_server_snippet'       => 'apache',
            'toolbox_generated_snippet'    => '',
            'debug_enabled'                => false,
            'debug_log_limit'              => 50,
            'general_module_cache'         => true,
            'general_module_optimize'      => true,
            'general_module_media'         => true,
            'general_module_cdn'           => true,
            'general_module_object_cache'  => true,
            'general_module_preload'       => true,
            'general_module_database'      => true,
            'general_module_toolbox'       => true,
            'general_module_debug'         => true,
            'heartbeat_control_admin'      => false,
            'heartbeat_control_admin_freq' => 60,
            'heartbeat_control_frontend'   => false,
            'heartbeat_control_front_freq' => 120,
            'heartbeat_control_post'       => false,
            'heartbeat_control_post_freq'  => 15,
            'import_export_last'           => '',
            'help_show_welcome'            => true,
            'bypass_cache_toggle'          => false,
            'per_post_ttl_default'         => 0,
        );
    }
}
